# Generated by Django 4.2.5 on 2024-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='dota_preview', verbose_name='Preview')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Описание')),
                ('video_src', models.FileField(upload_to='dota_video', verbose_name='Видео')),
                ('video_url', models.CharField(max_length=400, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='RustVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='rust_preview', verbose_name='Preview')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Описание')),
                ('video_src', models.FileField(upload_to='rust_video', verbose_name='Видео')),
                ('video_url', models.CharField(max_length=400, unique=True, verbose_name='URL')),
            ],
        ),
    ]
