# Generated by Django 4.2.5 on 2024-03-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotavideo',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dotavideo',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dotavideo',
            name='video_src',
            field=models.FileField(blank=True, upload_to='dota_video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='dotavideo',
            name='video_url',
            field=models.CharField(max_length=400, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='rustvideo',
            name='video_src',
            field=models.FileField(blank=True, upload_to='rust_video', verbose_name='Видео'),
        ),
    ]
